{%- set name = "diffpy.snmf" -%}
{%- set version = "0.1.0" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_snmf/diffpy_snmf-{{ version }}.tar.gz
  sha256: 2903bd7d9df588b35bd45bc07ea745c69fb281fb774beef8af645cebcb980b7c

build:
  preserve_egg_dir: true
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools >=62.0
    - pip

  run:
    - python >=3.10
    - setuptools >=62.0
    - numpy
    - scipy
    - cvxpy
    - diffpy.utils
    - numdifftools

test:
  imports:
    - diffpy.snmf

  requires:
    - pytest
    - flake8
    - codecov
    - coverage
    - pytest-env

about:
  home: https://github.com/diffpy/diffpy.snmf/
  summary: A python package implementing the stretched NMF algorithm.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    diffpy.snmf implements the stretched non negative matrix factorization (sNMF) and sparse stretched NMF (ssNMF) algorithms. This algorithm is designed to do an NMF factorization on a set of signals ignoring any uniform stretching of the signal on the independent variable axis. For example, for powder diffraction data taken from samples containing multiple chemical phases where the measurements were done at different temperatures and the materials were undergoing thermal expansion.
  doc_url: http://diffpy.github.io/diffpy.snmf/
  dev_url: https://github.com/diffpy/diffpy.snmf/

extra:
  recipe-maintainers:
    - sbillinge
